# Site settings
title: Rogue Rod Shop
email: roguerodshop@gmail.com
description: >
  TBD
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.roguerodshop.com" # the base hostname & protocol for your site
permalink: none

# Build settings
markdown: kramdown
